### ISSUE TITLE
use aws ec2 metadata for region config

### ISSUE THREAD

**Issue by trjstewart** [nginxinc/nginx-asg-sync#26]
**Is your feature request related to a problem? Please describe.**
I am currently planning a globally HA NGINX+ deployment and with the configuration options as they are currently it would mean we have to bake a separate AMI for each region, with this config being the only static portion of it.

**Describe the solution you'd like**
I would like to add an additional `self` option to the `region` configuration that uses the EC2 Metadata service to retrieve the current instance region.

```yaml
region: self
api_endpoint: http://127.0.0.1/api
sync_interval_in_seconds: 1
cloud_provider: AWS
upstreams:
 - name: nginx-poc-api
   autoscaling_group: nginx-poc-api
   port: 3000
   kind: http
```

**Describe alternatives you've considered**
I considered removing the `region` configuration all together and only using the EC2 Metadata service for configuration but I definitely think there is a use-case to allow for cross-region upstreams.
